output_dir: /results/rgb_2d_ucf101
encryption_key: nvidia_tao
model_config:
  model_type: rgb
  backbone: resnet18
  rgb_seq_length: 3
  rgb_pretrained_num_classes: 5
  input_type: 2d
  sample_strategy: consecutive
  dropout_ratio: 0.0
train_config:
  optim:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001
    lr_scheduler: MultiStep
    lr_steps: [5, 15, 20]
    lr_decay: 0.1
  epochs: 20
  checkpoint_interval: 1
dataset_config:
  train_dataset_dir: /data/train
  val_dataset_dir: /data/test
  label_map:
    ApplyEyeMakeup: 0
    ApplyLipstick: 1
    Archery: 2
    BabyCrawling: 3
    BalanceBeam: 4
    BandMarching: 5
    BaseballPitch: 6
    Basketball: 7
    BasketballDunk: 8
    BenchPress: 9
    Biking: 10
    Billiards: 11
    BlowDryHair: 12
    BlowingCandles: 13
    BodyWeightSquats: 14
    Bowling: 15
    BoxingPunchingBag: 16
    BoxingSpeedBag: 17
    BreastStroke: 18
    BrushingTeeth: 19
    CleanAndJerk: 20
    CliffDiving: 21
    CricketBowling: 22
    CricketShot: 23
    CuttingInKitchen: 24
    Diving: 25
    Drumming: 26
    Fencing: 27
    FieldHockeyPenalty: 28
    FloorGymnastics: 29
    FrisbeeCatch: 30
    FrontCrawl: 31
    GolfSwing: 32
    Haircut: 33
    HammerThrow: 34
    Hammering: 35
    HandstandPushups: 36
    HandstandWalking: 37
    HeadMassage: 38
    HighJump: 39
    HorseRace: 40
    HorseRiding: 41
    HulaHoop: 42
    IceDancing: 43
    JavelinThrow: 44
    JugglingBalls: 45
    JumpRope: 46
    JumpingJack: 47
    Kayaking: 48
    Knitting: 49
    LongJump: 50
    Lunges: 51
    MilitaryParade: 52
    Mixing: 53
    MoppingFloor: 54
    Nunchucks: 55
    ParallelBars: 56
    PizzaTossing: 57
    PlayingCello: 58
    PlayingDaf: 59
    PlayingDhol: 60
    PlayingFlute: 61
    PlayingGuitar: 62
    PlayingPiano: 63
    PlayingSitar: 64
    PlayingTabla: 65
    PlayingViolin: 66
    PoleVault: 67
    PommelHorse: 68
    PullUps: 69
    Punch: 70
    PushUps: 71
    Rafting: 72
    RockClimbingIndoor: 73
    RopeClimbing: 74
    Rowing: 75
    SalsaSpin: 76
    ShavingBeard: 77
    Shotput: 78
    SkateBoarding: 79
    Skiing: 80
    Skijet: 81
    SkyDiving: 82
    SoccerJuggling: 83
    SoccerPenalty: 84
    StillRings: 85
    SumoWrestling: 86
    Surfing: 87
    Swing: 88
    TableTennisShot: 89
    TaiChi: 90
    TennisSwing: 91
    ThrowDiscus: 92
    TrampolineJumping: 93
    Typing: 94
    UnevenBars: 95
    VolleyballSpiking: 96
    WalkingWithDog: 97
    WallPushups: 98
    WritingOnBoard: 99
    YoYo: 100
  output_shape:
  - 224
  - 224
  batch_size: 128
  workers: 2
  clips_per_video: 5
  augmentation_config:
    train_crop_type: no_crop
    horizontal_flip_prob: 0.5
    rgb_input_mean: [0.5]
    rgb_input_std: [0.5]
    val_center_crop: False
